name: "first-github-actions"
run-name: ${{ github.actor }} is learning github actions
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  print-hello-github:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: python main.py
